### ISSUE TITLE
ReuseExisting not works

### ISSUE THREAD

**Issue by gsgabrielsouza** [zblago/EF6TempTableKit#6]
Hi guys, a try to use this lib but i not understend a parameters ReuseExisting, i try reuse the same temp table but i receive the mensage 'Can't override query for temp table {tempTableName} as it is already attached to the context.'

 I'ts a issue ?

**Comment by zblago** [comment]
Hi Gabriel, 

we have covered that scenario with unit test - [ReuseSameTempTableWithUsingFlag](https://github.com/zblago/EF6TempTableKit/blob/master/tests/EF6TempTableKit.Test/UnitTest.cs). Take a look there and please provide at least one very simple scenario where you got this exception?

**Comment by gsgabrielsouza** [comment]
nice, thank's
